spring:
  profiles:
    active: dump

---
spring.profiles: local
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:noise-master;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: update

---
spring:
  profiles: major
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:file:./noise-master;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: false

---
spring:
  profiles: dump
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:file:./noise-master-dump;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: false
    show-sql: true